version: '3.8'

services:
  expo-app:
    build: .
    container_name: phlo-dev
    ports:
      - "8081:8081" # Metro bundler
    volumes:
      - ./:/app # Mapea todo el proyecto local al contenedor para Hot Reloading
      - /app/node_modules # Evita sobreescribir los node_modules del contenedor con los locales
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true # Permite interactuar con la consola de Expo (presionar 'w', 'a', 'i', etc.)
    tty: true
